#!/bin/bash

vagrant destroy --force
rm -fr certificates bin
vagrant up
export PATH=`pwd`/bin:$PATH
kubectl get componentstatuses --kubeconfig=certificates/admin.kubeconfig
kubectl get nodes --kubeconfig=certificates/admin.kubeconfig

